### PR TITLE
Basic Matlab reco

### PR DESCRIPTION
**Pull request by gBringout**
I have added three basic Matlab reconstruction for the frequency/calibration based reconstruction using published measurements of a FFP 3D Lissajous MPI scanner.

It was tested under windows and Matlab R2013a. It should also work under Linux.

### CODE REVIEW

**Comment by tknopp** [comment]
Wow, thanks. This is really cool.

Have you seen that there is a `kaczmarz.m` file in the matlab folder? Could you have a look if this works as well? There are options enable physical constraints.

I have nothing in principal against the ART from per christian. But the nice thing about our own implementation is that it is basically the same in Julia, Matlab, Python. So if one looks into the demo examples the code is very similar.

You should have commit rights now. So feel free to merge once you are ready. When #4 is resolved I will ping you so since it will require a code update.

**Comment by gBringout** [comment]
It is nice to participate to this project!

I have looked at `kaczmarz.m`, and I cannot really recognize the implementation. Especially the whole lambda and residual part. Is this a regularized Kaczmarz?

I would like that we clarify the implemented algorithm and then name accordingly the function. (This is why I have started with the script of P. C. Hansens, as it is, from my understanding, what was first published by Kaczmarz and described in the book of Natterer and Wübbeling. )

I will in the same time convert this function to matlab.

**Comment by tknopp** [comment]
Yes its the regularized Kaczmarz. Have a look at http://iopscience.iop.org/article/10.1088/0031-9155/55/6/003/meta  on page 1582. There the basic idea is explained. I have learned about this in (Saunders M 1995 Solution of sparse rectangular systems using LSQR and CRAIG BIT 35 588–604) although this is certainly not the first publication on the regularized Kaczmarz. There is also a Paper from Dax ("ON ROW RELAXATION METHODS FOR LARGE CONSTRAINED LEAST SQUARES PROBLEMS") that was used by the Philips group when they first discovered how good the algorithm performs in MPI.

But anyway, I actually do not care to much about the implementation. The code listed here should show that it is very simple to reconstruct MPI data. We should not get too deep into specific algorithms. In the Julia folder there is an SND and a Kaczmarz implementation. I think it would be best to mirror this in Matlab and Python.

The kaczmarz.m is by the way already Matlab code that we developed for the MathMPI network. I think Christian converted it from my Julia implementation, which is derived from a Python implementation that Anselm should be familiar with  ;-)

**Comment by gBringout** [comment]
ok, thanks for the information!

Could we then renamed the function (in all languages) as 'regularizedKaczmarz.m' ? It is clearer, I think.
I have tested the implementation and it is working perfectly!

**Comment by tknopp** [comment]
yes, lets do that. I am absolutely with you that we should be precise when naming the algorithms.

**Pull request merged**
