### PR TITLE
add matrix compression

### PR DESCRIPTION
**Pull request by tknopp**
This is a proposal for adding matrix compression to the MDF. I have implemented this within `MPIFiles.jl` including unit tests and it works pretty well. I request review by @hofmannmartin and @migrosser.

### CODE REVIEW

**Comment by tknopp** [comment]
Thanks, I am just wondering from the wording. Should we just replace the `basis` with `sparsity`?So this would then be `sparsityTransformation` `sparsityIndices` and `isSparsityTransformed`?

**Comment by migrosser** [comment]
I quite like that because it makes the naming more specific. I am wondering if there is a better name for sparsitiyIndices. So far I did not find one though.

**Comment by tknopp** [comment]
Hm yes. `sparseCoefficientsIndices` or just `coefficientsIndices` or `indicesOfCoefficients` or `sparseDataIndices`?

**Comment by tknopp** [comment]
Could you please also have a critical view on my wording "standard meaning of transformations". I am of course worried about the pre-factor. 

By the way, the plan is to create the package `https://github.com/tknopp/SparsityOperators.jl`, which we will use in `MPIFiles.jl` currently the later depends on `RegularizedLeastSquares` which is a pretty heavyweight dependency (see https://github.com/MagneticParticleImaging/MPIFiles.jl/issues/15). In `SparsityOperators.jl` we need to get the prefactors straight, once we have decided what we mean by "standard meaning".

**Comment by migrosser** [comment]
yes, both sparseCoefficientsIndices and sparseDataIndices sound good :)

The prefactors are of course a tricky question, because different communities use different prefactors. However, one could mention, that our implementations typically use the symmetrized/unitary normalization.

**Comment by tknopp** [comment]
yes, lets use the symmetric versions and specify this in this document. After we have done so, we actually need to fix `SparsityOperators.jl` since `DCT-II` and `DCT-IV` are not consistent.

What about FFT, we are applying  `fftshift`, which is not standard...

**Comment by hofmannmartin** [comment]
I would like to draw attention to a number of issues I have with this proposal:

1. We should reference some "standard" signal processing book or so, where the transformations are defined.
2. Why do we restrict cosine transformations to DCT I-IV? Why do not allow I-VIII?
3. At the moment I would find it really difficult to implement this new feature. The reason for this is that everything is written in prose. Could we for the sake of clarity and consistency add at least one or two formulas explaining how to uncompressed the data using `sparsityIndices`, `sparsityTransformation` and `data`? This would also solve the issue, where we do non-standard stuff like , e.g. when `sparsityTransformation` is `FFT`.
4. Related is the issue how to handle multidimensional transformation. How to use the single index in `sparsityIndices` in this scenario?
5. Is this specification able to handle the recent stuff Florian Lieb from Aschaffenburg did together with @tknopp?
6. The Changelog is missing an entry on what has been changed with the new version
7. The phrase **foreground** does not at all appear in the current version of the MDF and I would either not use it at all or give it a proper introduction. It could be difficult for a reader to grasp the meaning. E.g. the meaning in  `Flag, if the data is transformed along the (foreground) frame dimension` is unclear to me. Does this refer to the fast frame axis?
8. `In case that the $O$ foreground frames lay on a 2D or 3D grid (see \inlvar{/calibration/size}) we consider the multidimensional versions of the transformations.` We always have a 3D grid \inlvar{/calibration/size}). maybe something like: If `/calibration/size` exists we consider the three-dimensional versions of the transformations.
9. We should mention that this effectively allows "global" system matrix compression as introduced in [Lampe J, et al. 2012 Fast reconstruction in magnetic particle imaging Phys. Med. Biol. 57 1113–34].
10. I find the description of `sparsityIndices` too generic.

**Comment by hofmannmartin** [comment]
> Hm yes. `sparseCoefficientsIndices` or just `coefficientsIndices` or `indicesOfCoefficients` or `sparseDataIndices`?

I would really like if the field name starts by `sparsityTransformation`. So e.g. `sparsityTransformationCoefficientsIndices`

**Comment by tknopp** [comment]
> I would really like if the field name starts by sparsityTransformation. So e.g. sparsityTransformationCoefficientsIndices

That is 41 characters. :-)
Actually the indices have are not so much about the transformation but that the `data` field is sampled. We may also simply say `dataIndices`. It means that the `data` is subsampled at the indices. Or maybe `subsamplingIndices` is even more correct? @migrosser: What notation do we have in MRIReco?

**Comment by tknopp** [comment]
> 2. Why do we restrict cosine transformations to DCT I-IV? Why do not allow I-VIII?

Was not aware of the others. The question here is also not completeness, but what is easily accessible in Julia, Matlab, Python, C. We want that people can easily invert those transformations.
I know that DCT I-IV are accessible in Julia / Python.

**Comment by tknopp** [comment]
We may even drop `FFT` to simplify things. FFT will not be used anyway, because it as worse compression rates.

**Comment by tknopp** [comment]
In our MRI package, we indeed call it simply `subsamplingIndices`, see
https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/master/src/Datatypes/AcqData.jl line 23. I think this describes quite well its purpose.

**Comment by tknopp** [comment]
> 6. The Changelog is missing an entry on what has been changed with the new version

Added in the last commit.

**Comment by tknopp** [comment]
> 1. We should reference some "standard" signal processing book or so, where the transformations are defined.

yes, this is on the TODO list. In that case linking to FFTW may also be a good strategy since this is a well respected package, where also the mathematics are well defined.

**Comment by tknopp** [comment]
> 7. The phrase foreground does not at all appear in the current version of the MDF and I would either not use it at all or give it a proper introduction. 

ok, this was missing. But it is easy to introduce it. We could also talk about "non-background" which would be well defined but I favor using "background / foreground" 

> It could be difficult for a reader to grasp the meaning. E.g. the meaning in Flag, if the data is transformed along the (foreground) frame dimension is unclear to me. Does this refer to the fast frame axis?

Hm. What is unclear specifically? We just apply the transformation to the foreground frames and ignore the background frames. To make this more convenient we make it mandatory that the BG frames are sorted to the end.

**Comment by tknopp** [comment]
> 5. Is this specification able to handle the recent stuff Florian Lieb from Aschaffenburg did together with tknopp?

I am not 100% sure but tend to say yes. Florian was more investigating background removal and not the actual storage. He used regular DCTs.

**Comment by tknopp** [comment]
> 4. Related is the issue how to handle multidimensional transformation. How to use the single index in sparsityIndices in this scenario?

This is clear isn't it? The foreground frames dimension (now named O) represent a 3D space, which is described in other places of this document. That we reshape that space into a vector should be clear.  See also `/calibration/positions`.

**Comment by tknopp** [comment]
> In case that the $O$ foreground frames lay on a 2D or 3D grid (see \inlvar{/calibration/size}) we consider the multidimensional versions of the transformations. We always have a 3D grid \inlvar{/calibration/size}). maybe something like: If /calibration/size exists we consider the three-dimensional versions of the transformations.

Hm, in case of singleton dimensions, those transformations are the same. Technically you are right, but in case of e.g. "N x 1 x 1" we would talk about a 1D calibration measurement or a 1D grid. That we store this in 3D is more about convenience.

**Comment by hofmannmartin** [comment]
> > 1. Why do we restrict cosine transformations to DCT I-IV? Why do not allow I-VIII?
> 
> Was not aware of the others. The question here is also not completeness, but what is easily accessible in Julia, Matlab, Python, C. We want that people can easily invert those transformations.
> I know that DCT I-IV are accessible in Julia / Python.

Regarding this it might be a good idea to use those defined within `FFTW`

**Comment by tknopp** [comment]
> Regarding this it might be a good idea to use those defined within FFTW

This is, what we are actually doing:

http://www.fftw.org/fftw3_doc/1d-Real_002deven-DFTs-_0028DCTs_0029.html

We should just document more that we are using FFTWs definitions.

**Comment by hofmannmartin** [comment]
> > 1. The phrase foreground does not at all appear in the current version of the MDF and I would either not use it at all or give it a proper introduction.
> 
> ok, this was missing. But it is easy to introduce it. We could also talk about "non-background" which would be well defined but I favor using "background / foreground"
> 
> > It could be difficult for a reader to grasp the meaning. E.g. the meaning in Flag, if the data is transformed along the (foreground) frame dimension is unclear to me. Does this refer to the fast frame axis?
> 
> Hm. What is unclear specifically? We just apply the transformation to the foreground frames and ignore the background frames. To make this more convenient we make it mandatory that the BG frames are sorted to the end.

So it might be better to write: Flag, if the foreground frames are compressed along the frame dimension.

**Comment by hofmannmartin** [comment]
As a general note would it not be better to use the term compression wherever possible.

Simply put within the MDF we would like to highlight that the data is compressed and describe how to compress/uncompress it. In this regard I see the MDF as a tool for storage and exchange. I see the sparsity transformation more as a tool. Therefore, I find the intense usage of the term "sparsity transform" sub-optimal.

**Comment by hofmannmartin** [comment]
> > In case that the $O$ foreground frames lay on a 2D or 3D grid (see \inlvar{/calibration/size}) we consider the multidimensional versions of the transformations. We always have a 3D grid \inlvar{/calibration/size}). maybe something like: If /calibration/size exists we consider the three-dimensional versions of the transformations.
> 
> Hm, in case of singleton dimensions, those transformations are the same. Technically you are right, but in case of e.g. "N x 1 x 1" we would talk about a 1D calibration measurement or a 1D grid. That we store this in 3D is more about convenience.

However, in this case we should include this into the specification that the conditionality of the transformation depends on the number of singleton dimensions in `/calibration/size`, since this was not clearly communicated.

**Comment by tknopp** [comment]
> As a general note would it not be better to use the term compression wherever possible.
> Simply put within the MDF we would like to highlight that the data is compressed and describe how to compress/uncompress it. In this regard I see the MDF as a tool for storage and exchange. I see the sparsity transformation more as a tool. Therefore, I find the intense usage of the term "sparsity transform" sub-optimal.

Hm, this has pros and cons. I would call the removal of frequency components also one kind of compression. Than we have two types of compression. Frequency removal and sparsity transformation.

**Comment by tknopp** [comment]
> So it might be better to write: Flag, if the foreground frames are compressed along the frame dimension.

done

**Comment by tknopp** [comment]
> 3. At the moment I would find it really difficult to implement this new feature. The reason for this is that everything is written in prose. Could we for the sake of clarity and consistency add at least one or two formulas explaining how to uncompressed the data using sparsityIndices, sparsityTransformation and data? This would also solve the issue, where we do non-standard stuff like , e.g. when sparsityTransformation is FFT.

I am not 100% sure what formula we should integrate. Of course its mostly prose but that is also the case for the other transformations. I am somewhat in favor, that we add formula that describes the `subsamplingIndices`. I am not sure about DCT. There I find a reference better. If you still want this, lets put it into an additional section, where the sparsity transformations are fully specified.

**Comment by hofmannmartin** [comment]
> > 1. Related is the issue how to handle multidimensional transformation. How to use the single index in sparsityIndices in this scenario?
> 
> This is clear isn't it? The foreground frames dimension (now named O) represent a 3D space, which is described in other places of this document. That we reshape that space into a vector should be clear. See also `/calibration/positions`.

Ok maybe I missed the point with my question.

If I have a 3D transform and an index 10 with corresponding coefficient in `data` what is the basis vector of my transformation corresponding to 10? So I am really interested in the mapping between index and basis vector, which is clear to me in 1D, but not so in >1D.

**Comment by hofmannmartin** [comment]
> > As a general note would it not be better to use the term compression wherever possible.
> > Simply put within the MDF we would like to highlight that the data is compressed and describe how to compress/uncompress it. In this regard I see the MDF as a tool for storage and exchange. I see the sparsity transformation more as a tool. Therefore, I find the intense usage of the term "sparsity transform" sub-optimal.
> 
> Hm, this has pros and cons. I would call the removal of frequency components also one kind of compression. Than we have two types of compression. Frequency removal and sparsity transformation.

It is true that frequency removal is also a kind of compression, however in the document we have phrased this differently and speak of frequency selection. On the other hand DCT has been long used for compression in the signal processing community (e.g. jpeg). Maybe we refer to this kind of compression to as image compression, since this is what it is?

**Comment by tknopp** [comment]
> If I have a 3D transform and an index 10 with corresponding coefficient in data what is the basis vector of my transformation corresponding to 10? So I am really interested in the mapping between index and basis vector, which is clear to me in 1D, but not so in >1D.

Here is the code: https://github.com/MagneticParticleImaging/MPIFiles.jl/blob/master/src/MDF.jl#L342

**Comment by hofmannmartin** [comment]
> > 1. At the moment I would find it really difficult to implement this new feature. The reason for this is that everything is written in prose. Could we for the sake of clarity and consistency add at least one or two formulas explaining how to uncompressed the data using sparsityIndices, sparsityTransformation and data? This would also solve the issue, where we do non-standard stuff like , e.g. when sparsityTransformation is FFT.
> 
> I am not 100% sure what formula we should integrate. Of course its mostly prose but that is also the case for the other transformations. I am somewhat in favor, that we add formula that describes the `subsamplingIndices`. I am not sure about DCT. There I find a reference better. If you still want this, lets put it into an additional section, where the sparsity transformations are fully specified.

I would prefer to have like one very generic formula which covers all transformations and then leave the specifics on detailed transformations to a good reference. Maybe one simple example with DCT-II or so. I definitely support describing `subsamplingIndices` by a formula.

**Comment by hofmannmartin** [comment]
> > If I have a 3D transform and an index 10 with corresponding coefficient in data what is the basis vector of my transformation corresponding to 10? So I am really interested in the mapping between index and basis vector, which is clear to me in 1D, but not so in >1D.
> 
> Here is the code: https://github.com/MagneticParticleImaging/MPIFiles.jl/blob/master/src/MDF.jl#L342

And that was my point currently the details on what to to with `subsamplingIndices` is in some software package. Taking  the point of view of a user that is not us and not so familiar with compression techniques I would not really know what to do with the data and where to find help with the current version. Therefore, I would like to have this written down in the specs.

**Comment by tknopp** [comment]
My last commit:
- added a mathematical description of the general sparsity transformation as well as the subsamplingIndices
- links to FFTW
- discusses that the dimensionality of the transformation is linked to the number of singleton dimensions in /calibration/size

Also we speak more about "compression" now. But I am not sure if you also want to rename the fields. `sparsityTransformation` is pretty clear IMHO. And if we use that, I still think `isSparsityTransformed` is pretty precise. While `isCompressed` might describe better from a high level perspective what is done, the user is much more interested, how the data is transformed.

I am actually not sure if I have now addressed all your points. Please have a look.

**Comment by hofmannmartin** [comment]
Surnames in references 8 and 9 are missing.

**Comment by hofmannmartin** [comment]
> The compression option, indicated by the flag `isSparsityTransformed`, is only available if the processing stages indicated by `isFastFrameAxis`, `isFourierTransformed`, and `isFramePermutation` have been applied. The frames need to be permuted in such a way that first _O_ frames are the foreground frames and the last _E_ frames are the background frames.

Is it not better to check `isBackgroundFrame` if the foreground and background frames are in the correct order?

Moreover, if I measure without background measurement or only one background measurement at the end, why should I permute frames? In this scenario the dependency on `isFramePermutation` makes no sense.

**Comment by hofmannmartin** [comment]
> The sparsity transformation is only applied to the _O_ foreground frames. Let ...

would make a new paragraph from "Let" on.

**Comment by hofmannmartin** [comment]
I also would suggest using a different symbol for the restored u tilde, since it is mathematically not the same as the originally defined u tilde.

**Comment by hofmannmartin** [comment]
Moreover, I would suggest to add the inversion formula for the sake of completeness to make it as simple as possible for a reader. Especially since many users will likely only uncompress data.

**Comment by hofmannmartin** [comment]
> But I am not sure if you also want to rename the fields. `sparsityTransformation` is pretty clear IMHO. And if we use that, I still think `isSparsityTransformed` is pretty precise. While `isCompressed` might describe better from a high level perspective what is done, the user is much more interested, how the data is transformed.

I do like the field names as they are now.

**Comment by hofmannmartin** [comment]
> Indices of the coefficients (between 1 and O)

I would like to update this to something like: "Subsampling indices $\beta_{j,c,w,b}$"

**Comment by hofmannmartin** [comment]
The new fields need to be put into the correct spots, such that the Parameter column is in alphabetical order.

**Comment by tknopp** [comment]
> I also would suggest using a different symbol for the restored u tilde, since it is mathematically not the same as the originally defined u tilde.

suggestion? We then also need the same for \hat{u}

**Comment by hofmannmartin** [comment]
> > I also would suggest using a different symbol for the restored u tilde, since it is mathematically not the same as the originally defined u tilde.
> 
> suggestion? We then also need the same for \hat{u}

That is true.

I would like to have it distinct, to emphasize that this compression is lossy. Maybe it would also be a good idea to insert this fact into the text.

**Comment by hofmannmartin** [comment]
> > The compression option, indicated by the flag `isSparsityTransformed`, is only available if the processing stages indicated by `isFastFrameAxis`, `isFourierTransformed`, and `isFramePermutation` have been applied. The frames need to be permuted in such a way that first _O_ frames are the foreground frames and the last _E_ frames are the background frames.
> 
> Is it not better to check `isBackgroundFrame` if the foreground and background frames are in the correct order?
> 
> Moreover, if I measure without background measurement or only one background measurement at the end, why should I permute frames? In this scenario the dependency on `isFramePermutation` makes no sense.

Do we want to leave the hint that `isBackgroundFrame` can be used to check if the order is correct?

**Comment by tknopp** [comment]
\tilde{v} and \hat{v}. Or do we use v in other places?

**Comment by hofmannmartin** [comment]
> \tilde{v} and \hat{v}. Or do we use v in other places?

no we do not.

**Comment by hofmannmartin** [comment]
> setting it to 0 for all $n$ that are not contained in $\beta_{j,c,w,b}$

replace by: setting it to 0 elsewhere.

**Comment by hofmannmartin** [comment]
> In case of unitary transformations, the inversion can done by

can **be**

**Comment by tknopp** [comment]
You may want to fix smaller typos directly here in Github on the branch.

**Comment by hofmannmartin** [comment]
> You may want to fix smaller typos directly here in Github on the branch.

I do not see any more typos and am quite satisfied with the result. Do we want to have Marija have a look, or should I merge the request?

**Comment by tknopp** [comment]
If Marija can have a quick look that would be great. Then, please merge and could you handle the release of the arxiv document? In the meantime I will update MPIFiles. We then also need to update some MDFs, e.g. in the MPIReco tests. I will do this. Thanks for the review!

**Comment by hofmannmartin** [comment]
> If Marija can have a quick look that would be great. Then, please merge and could you handle the release of the arxiv document? In the meantime I will update MPIFiles. We then also need to update some MDFs, e.g. in the MPIReco tests. I will do this. Thanks for the review!

I will do the arXiv release.

For the update of the MDFs you can have a look at my crawler in  `mpiresults/20190809mpidataCrawler`.

**Comment by hofmannmartin** [comment]
@tknopp currently we compress the time domain data. This is a mistake right. To change this we need to exchange the index W->K same with small letter index.

**Comment by tknopp** [comment]
yes, mistake, please change!

**Pull request merged**
